database:
  mongodb:
    host: localhost
    port: 27017
    database: timeline
    username: 
    password: 
    auth_source: admin

cache:
  redis:
    host: 192.168.253.99
    port: 6379
    db: 0
    password: "123456"
    ttl: 3600  # Default TTL in seconds
    prefix: "timeline:"

server:
  title: "World History Timeline"
  version: "v1.0.0"
  host: "0.0.0.0"
  port: 8000
  workers: 1

environment: "development"

auth:
  jwt:
    secret_key: "change-this-to-a-random-secret-key"
    algorithm: "HS256"
    access_token_expire_minutes: 30

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/app.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
    performance:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/performance.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
  loggers:
    "":  # Root logger
      level: INFO
      handlers: [console, file]
      propagate: true
    performance:
      level: INFO
      handlers: [performance]
      propagate: false
    uvicorn:
      level: INFO
      handlers: [console, file]
      propagate: false

cors:
  allowed_origins: ["*"]  # Change in production
  allowed_methods: ["*"]
  allowed_headers: ["*"]
  allow_credentials: true

rate_limiting:
  enabled: true
  rate: 100  # requests per minute
  burst: 200  # maximum burst size

monitoring:
  alerts:
    avg_response_time: 1.0  # seconds
    p95_response_time: 2.0  # seconds
    error_rate: 0.05  # 5%
    request_rate: 100  # requests per minute
  metrics:
    window_size: 3600  # 1 hour of data retention

admin:
  login_logo_url: "/static/images/admin-logo.png"
  logo_url: "/static/images/logo.png"
  favicon_url: "/static/images/favicon.ico"
